# use goreleaser for builds and containers; only x86_64 builds for Linux and
# Windows are needed for GCP.
---
project_name: google-f5-preflight-checklist
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}-{{ .Commit }}
    # TODO: @memes - expand this list as needed
    goos:
      - linux
      - windows
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - --batch
      - --local-user
      - '{{ .Env.GPG_FINGERPRINT }}'
      - --output
      - '${signature}'
      - --detach-sign
      - '${artifact}'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - memes/{{ .ProjectName }}:latest
      - memes/{{ .ProjectName }}:{{ .Tag }}
      - memes/{{ .ProjectName }}:{{ .Major }}
    dockerfile: Dockerfile
    use: docker
    build_flag_templates:
      # yamllint disable rule:line-length
      - "--pull"
      - "--label=maintainer=Matthew Emes <memes@matthewemes.com>"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.authors=memes@matthewemes.com"
      - "--label=org.opencontainers.image.description=Perform a preflight check before deploying F5 products in GCP"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}/tree/{{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation={{ .GitURL }}/tree/{{ .FullCommit }}/README.md"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}"
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.description=Perform a preflight check before deploying F5 products in GCP"
      - "--label=org.label-schema.name={{ .ProjectName }}"
      - "--label=org.label-schema.vcs-url={{ .GitURL }}/tree/{{ .FullCommit }}"
      - "--label=org.label-schema.usage={{ .GitURL }}/tree/{{ .FullCommit }}/README.md"
      - "--label=org.label-schema.version={{ .Version }}"
      - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"
      - "--label=org.label-schema.url={{ .GitURL }}"
      - "--label=org.label-schema.license=MIT"
      # yamllint enable rule:line-length
release:
  draft: false
  prerelease: auto
milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"
